<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityManager;

/**
 * TirelireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TirelireRepository extends \Doctrine\ORM\EntityRepository
{
    public function getTotalAmount(){

        return $this->createQueryBuilder('t')
            ->select('SUM(t.montant)')
            ->getQuery()
            ->getSingleScalarResult();

    }
}
